add sample doc for companion app
ms-iot/content pull request #1016
Opened 2016-12-01 23:33 UTC by bfjelds

2016-12-05 21:46 UTC, derekameer commented on en-US/Samples/CompanionApp.md
> +samplelink: N/A
https://github.com/ms-iot/samples/tree/develop/CompanionApp ?

2016-12-05 21:47 UTC, derekameer commented on en-US/Samples/CompanionApp.md
> +You can find the source code for this sample by downloading a zip of all of our samples [here](https://github.com/ms-iot/samples/archive/develop.zip) and navigating to the `samples-develop\CompanionA
Generally want to avoid links using the word "here", maybe "though the Samples GitHub repository"?

2016-12-05 21:48 UTC, derekameer commented on en-US/Samples/CompanionApp.md
> +1. Connect to your IotCore device using [SSH]({{site.baseurl}}/{{page.lang}}/Docs/SSH) or [PowerShell]({{site.baseurl}}/{{page.lang}}/Docs/PowerShell) and run the following commands to enable SoftAP
IotCore -> IoT Core

2016-12-05 21:49 UTC, derekameer commented on en-US/Samples/CompanionApp.md
> +1. the Client - running on an Android or Windows Phone 10 phone, this app will find your IotCore device, connect to it, and allow you to specify the required information to join a WiFi network.
IotCore -> IoT Core (same throughout the doc)

2016-12-05 21:50 UTC, dcrck requested changes
Looks good, see comments for some minor suggestions

2016-12-05 21:54 UTC, bfjelds commented on en-US/Samples/CompanionApp.md
> +You can find the source code for this sample by downloading a zip of all of our samples [here](https://github.com/ms-iot/samples/archive/develop.zip) and navigating to the `samples-develop\CompanionA
this is pretty much boiler-plate code

2016-12-05 23:09 UTC, bfjelds commented on en-US/Samples/CompanionApp.md
> +samplelink: N/A
done

2016-12-05 23:10 UTC, bfjelds commented on en-US/Samples/CompanionApp.md
> +1. the Client - running on an Android or Windows Phone 10 phone, this app will find your IotCore device, connect to it, and allow you to specify the required information to join a WiFi network.
done

2016-12-07 00:27 UTC, rachitb777 commented
👍

2016-12-07 00:27 UTC, merged