added documentation for OICAdapter alljoyn bridge
ms-iot/content pull request #1096
Opened 2017-03-16 19:05 UTC by javiddhankwala

2017-03-16 19:05 UTC, msftclas commented
@__javiddhankwala__,
Thanks for your contribution.
To ensure that the project team has proper rights to use your work, please complete the Contribution License Agreement at https://cla.microsoft.com.

It will cover your contributions to all Microsoft-managed open source projects.
_Thanks,
Microsoft Pull Request Bot_

2017-03-16 22:36 UTC, msftclas commented
__@javiddhankwala__, thanks for signing the contribution license agreement. We will now validate the agreement and then the pull request.
<br />_Thanks, Microsoft Pull Request Bot_

2017-03-20 17:41 UTC, zhuridartem requested changes

2017-03-20 17:41 UTC, zhuridartem commented on en-US/Docs/AllJoynDSB.md
> +layout: default
These newlines are non-compatible.

2017-03-20 17:41 UTC, zhuridartem commented on en-US/Samples/OICAdapter.md
> +layout: sample
non-compatible ^M

2017-03-23 00:24 UTC, msftclas commented
__@javiddhankwala__, thanks for signing the contribution license agreement. We will now validate the agreement and then the pull request.
<br />_Thanks, Microsoft Pull Request Bot_

2017-03-23 00:25 UTC, closed without merging

2017-03-23 00:25 UTC, javiddhankwala commented
Had to delete my fork. Have submitted another pull request with the changes requested