Update Downloads.md
ms-iot/content pull request #1292
Opened 2017-12-01 19:55 UTC by saraclay

2017-12-01 20:59 UTC, SlavyMihov approved these changes

2017-12-01 22:28 UTC, paulmon requested changes
link should be https://github.com/ms-iot/python/releases/tag/v1.5Alpha

2017-12-04 18:19 UTC, SlavyMihov approved these changes

2017-12-04 18:31 UTC, paulmon approved these changes

2017-12-04 18:56 UTC, bfjelds approved these changes

2017-12-04 18:56 UTC, merged